#[cfg(test)]
mod tests {
    //use crate::parsing::{AnField, pieces::Piece};
    use crate::logic::best_move::find_best_move;
    use crate::logic::valid_placement::is_valid_placement;
    use crate::logic::read_input::read_input;

    /// Vérifie que la première pièce peut être placée même si elle ne touche pas de cellule alliée
    #[test]
    fn test_first_turn_placement() {
        let input = "\
$$$ exec p1 : [linux_robots/h2_d2]
Anfield 20 15:
01234567890123456789
000 ....................
001 ....................
002 .........@..........
003 ....................
004 ....................
005 ....................
006 ....................
007 ....................
008 ....................
009 ....................
010 ....................
011 ....................
012 .........$..........
013 ....................
014 ....................
Piece 3 2:
O..
O..
";

        let game_state = read_input(1, input);
        let (x, y) = find_best_move(&game_state.anfield, &game_state.anfield.piece, true);

        assert!(x < game_state.anfield.width as usize && y < game_state.anfield.length as usize, 
            "La position doit être dans les limites.");
    }

    /// Vérifie qu'une pièce peut être placée juste en dessous d'une autre
    #[test]
    fn test_vertical_extension() {
        let input = "\
$$$ exec p1 : [linux_robots/h2_d2]
Anfield 20 15:
01234567890123456789
000 ....................
001 .........a..........
002 .........a..........
003 ....................
004 ....................
005 ....................
006 ....................
007 ....................
008 ....................
009 ....................
010 ....................
011 ....................
012 .........$..........
013 ....................
014 ....................
Piece 1 2:
O
O
";

        let game_state = read_input(1, input);
        let (x, y) = find_best_move(&game_state.anfield, &game_state.anfield.piece, false);

        assert_eq!((x, y), (9, 3), "La pièce doit être placée verticalement sous une autre.");
    }

    /// Vérifie qu'on ne peut pas placer une pièce dans une case déjà occupée par l'ennemi
    #[test]
    fn test_invalid_placement_enemy_overlap() {
        let input = "\
$$$ exec p1 : [linux_robots/h2_d2]
Anfield 10 10:
0123456789
000 ..........
001 ..........
002 .........@
003 ..........
004 ..........
005 ..........
006 .........$
007 ..........
008 ..........
009 ..........
Piece 2 2:
O.
O.
";

        let game_state = read_input(1, input);
        let result = is_valid_placement(&game_state.anfield, &game_state.anfield.piece, 8, 6, false);
        assert_eq!(result, false, "Une pièce ne doit pas recouvrir une cellule ennemie.");
    }

    /// Vérifie que `find_best_move()` choisit un bon placement stratégique
    #[test]
    fn test_find_best_move() {
        let input = "\
$$$ exec p1 : [linux_robots/h2_d2]
Anfield 20 15:
01234567890123456789
000 ....................
001 ....................
002 .........@..........
003 .........a..........
004 .........a..........
005 ....................
006 ....................
007 ....................
008 ....................
009 ....................
010 ........$sss........
011 ........$$..........
012 .........$..........
013 ....................
014 ....................
Piece 3 2:
...
OO.
";

        let game_state = read_input(1, input);
        let (x, y) = find_best_move(&game_state.anfield, &game_state.anfield.piece, false);

        assert_eq!((x, y), (8, 3), "find_best_move() doit placer la pièce intelligemment.");
    }

    /// Vérifie que la pièce est bien placée lorsqu'il faut prioriser le contact avec une cellule alliée
    #[test]
    fn test_contact_with_ally() {
        let input = "\
$$$ exec p1 : [linux_robots/h2_d2]
Anfield 20 15:
01234567890123456789
000 ....................
001 ....................
002 .........@..........
003 .........@..........
004 ........aa..........
005 ....................
006 ....................
007 ....................
008 .......s............
009 .......ss...........
010 .......ss$$$........
011 ........$$..........
012 .........$..........
013 ....................
014 ....................
Piece 2 1:
OO
";

        let game_state = read_input(1, input);
        let (x, y) = find_best_move(&game_state.anfield, &game_state.anfield.piece, false);

        assert_eq!((x, y), (7, 4), "La pièce doit être placée au bon endroit.");
    }

    /// Vérifie que `find_best_move()` ne place pas une pièce hors de la grille
    #[test]
    fn test_invalid_placement_outside_grid() {
        let input = "\
$$$ exec p1 : [linux_robots/h2_d2]
Anfield 10 10:
0123456789
000 ..........
001 ..........
002 .........@
003 ..........
004 ..........
005 ..........
006 ..........
007 ..........
008 ..........
009 ..........
Piece 3 2:
OO.
..O
";

        let game_state = read_input(1, input);
        let result = is_valid_placement(&game_state.anfield, &game_state.anfield.piece, 9, 9, false);
        assert_eq!(result, false, "Une pièce ne doit pas pouvoir être placée en dehors de la grille.");
    }

    /// Vérifie qu'une pièce avec un point d'ancrage partiel est bien prise en compte
    #[test]
    fn test_piece_partial_contact() {
        let input = "\
$$$ exec p1 : [linux_robots/h2_d2]
Anfield 20 15:
01234567890123456789
000 ....................
001 ....................
002 .........@..........
003 .........@..........
004 .......aa@..........
005 ....................
006 ....................
007 ....................
008 .......ss...........
009 .......$$...........
010 .......$$$$$........
011 ........$$..........
012 .........$..........
013 ....................
014 ....................
Piece 4 2:
..O.
..O.
";

        let game_state = read_input(1, input);
        let (x, y) = find_best_move(&game_state.anfield, &game_state.anfield.piece, false);

        assert_eq!((x, y), (5, 4), "find_best_move() doit bien gérer les pièces partiellement connectées.");
    }
}
