mod parsing;
mod logic;
mod display;

use logic::read_input::read_input;
use logic::best_move::find_best_move;
use logic::print_move::print_move;

fn main() {
    let mut player = 0;
    loop {
        // Lire l'état du jeu via read_input
        let (player_n, complete_input) = get_stdin();

        if player_n != 0 {
            player = player_n;

        }

        let game_state = read_input(player, complete_input.as_str());
        // println!("here {:?}",game_state.anfield);
        // Trouver la meilleure position
        let (x, y) = find_best_move(&game_state.anfield, &game_state.anfield.piece);

        // Afficher la position choisie
        print_move(x, y);
    }
}
pub fn get_stdin() -> (usize, String) {
    let mut complete_input = String::new();
    let mut end_loop = (false, 0);
    let mut player_n: usize = 0;

    // Read the first line separately to extract the player number
    let mut first_line = String::new();
    std::io::stdin().read_line(&mut first_line).expect("Failed to read input");
    
    complete_input += &first_line;

    if first_line.starts_with("$$$ exec") {
        let parts: Vec<&str> = first_line.split_whitespace().collect();
        if parts.len() >= 3 {
            if let Some(player_str) = parts.get(2) {
                player_n = player_str.trim_start_matches('p').parse().unwrap_or(0);
            }
        }
    }

    loop {
        let mut input = String::new();
        std::io::stdin().read_line(&mut input).expect("Failed to read input");

        complete_input += &input;

        if input.starts_with("Piece") {
            let tmp: Vec<&str> = input.split_whitespace().collect();
            let mut t = tmp[tmp.len() - 1];
            t = t.trim_matches(':');

            end_loop.0 = true;
            end_loop.1 = t.parse().unwrap();

            continue;
        }

        if end_loop.0 {
            end_loop.1 -= 1;

            if end_loop.1 == 0 {
                break;
            }
        }
    }

    (player_n, complete_input)
}

/*
$$$ exec p1 : [linux_robots/h2_d2]
Anfield 20 15:
    01234567890123456789
000 ....................
001 ....................
002 .........@..........
003 ....................
004 ....................
005 ....................
006 ....................
007 ....................
008 ....................
009 ....................
010 ....................
011 ....................
012 .........$..........
013 ....................
014 ....................
Piece 3 2:
O..
O..
-> Answer (@): 9 2

Anfield 20 15:
    01234567890123456789
000 ....................
001 .........a..........
002 .........a..........
003 ....................
004 ....................
005 ....................
006 ....................
007 ....................
008 ....................
009 ....................
010 ....................
011 ....................
012 .........$..........
013 ....................
014 ....................
Piece 1 2:
O
O
-> Answer (@): 9 3


Anfield 20 15:
    01234567890123456789
000 ....................
001 ....................
002 .........@..........
003 .........a..........
004 .........a..........
005 ....................
006 ....................
007 ....................
008 ....................
009 ....................
010 ........$sss........
011 ........$$..........
012 .........$..........
013 ....................
014 ....................
Piece 3 2:
...
OO.
-> Answer (@): 8 3 // 9 4 false

Anfield 20 15:
    01234567890123456789
000 ....................
001 ....................
002 .........@..........
003 .........@..........
004 ........aa..........
005 ....................
006 ....................
007 ....................
008 .......s............
009 .......ss...........
010 .......ss$$$........
011 ........$$..........
012 .........$..........
013 ....................
014 ....................
Piece 2 1:
OO
-> Answer (@): 7 4

Anfield 20 15:
    01234567890123456789
000 ....................
001 ....................
002 .........@..........
003 .........@..........
004 .......aa@..........
005 ....................
006 ....................
007 ....................
008 .......ss...........
009 .......$$...........
010 .......$$$$$........
011 ........$$..........
012 .........$..........
013 ....................
014 ....................
Piece 4 2:
..O.
..O.
-> Answer (@): 5 4

Anfield 20 15:
    01234567890123456789
000 ....................
001 ....................
002 .........@..........
003 .........@..........
004 .......a@@..........
005 .......a............
006 ....................
007 ......ss............
008 ......ss$...........
009 .......$$...........
010 .......$$$$$........
011 ........$$..........
012 .........$..........
013 ....................
014 ....................
Piece 3 2:
.O.
.OO
-> Answer (@): 6 5

*/